name: Run Python script

on:
  push:
    branches:
      - main   # Trigger the action when code is pushed to the main branch
  
jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Use the appropriate version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
         # Install dependencies if you have any

    - name: Run Python script
      run: |
        python file.py# Replace with the actual name of your Python script
